
services:

  # 初回起動時ではセーブデータ読み込みを特別な方法で行う必要がある
  # 読み込みたいデータを volume-save/save/first.sve に配置し、まずはこれを起動する
  # そして、Simutransのアプリを自身の端末で起動し、一度サーバーに接続する(これにより適切な初期設定が行われる)
  first:
    build:
      context: server
      dockerfile: Dockerfile.general
    restart: "no"
    ports:
      - "${PORT}:13353"
    volumes:
      - ./volume-bin:/app/bin
      - ./volume-save:/root/simutrans
    command:
      /app/bin/simutrans-extended
        -objects Pak128.Britain-Ex
        -server 13353
        -debug 2
        -server_admin_pw ${NETTOOL_PASSWORD}
        -load first.sve
    networks:
      default:
        aliases:
          - server

  # 通常の実行環境
  # GUIを動かすために必要なライブラリが全て入っている
  # ただし、GUIに接続することはできない
  server-general:
    build:
      context: server
      dockerfile: Dockerfile.general
    restart: unless-stopped
    ports:
      - "${PORT}:13353"
    volumes:
      - ./volume-bin:/app/bin
      - ./volume-save:/root/simutrans
    command:
      /app/bin/simutrans-extended
        -objects Pak128.Britain-Ex
        -server 13353
        -debug 2
        -server_admin_pw ${NETTOOL_PASSWORD}
    networks:
      default:
        aliases:
          - server

  # headlessビルド用の実行環境(GUIの描画がないため負荷が少ない)
  # https://bridgewater-brunel.me.uk/downloads/nightly/linux-x64/command-line-server-build/
  # からダウンロードし、headless-serverという名前でvolume-binに配置しておくこと
  server-headless:
    build:
      context: server
      dockerfile: Dockerfile.headless
      args:
        - SIMUTRANS_VERSION=${SIMUTRANS_VERSION}
    restart: unless-stopped
    ports:
      - "${PORT}:13353"
    volumes:
      - ./volume-bin/pak:/app/bin/pak
      - ./volume-save:/root/simutrans
    command:
      /app/bin/headless-server
        -objects pak
        -server 13353
        -debug 2
        -server_admin_pw ${NETTOOL_PASSWORD}
        -load ../server13353-network.sve
    networks:
      default:
        aliases:
          - server
  # vncでGUIに接続できる実行環境
  # プロセス終了時に自動で復帰する機構付き
  server-vnc:
    build:
      context: server
      dockerfile: Dockerfile.vnc
    restart: unless-stopped
    ports:
      - "${PORT}:13353"   # simutrans-extendedのポート
      - "5900:5900"     # VNCのポート
    volumes:
      - ./volume-bin:/app/bin
      - ./volume-save:/root/simutrans
    environment:
      - COMMAND=/app/bin/simutrans-extended
        -objects Pak128.Britain-Ex
        -server 13353
        -fullscreen
        -debug 2
        -server_admin_pw ${NETTOOL_PASSWORD}
    command: /app/start-vnc.sh
    networks:
      default:
        aliases:
          - server

  # オートセーブ・バックアップ用コンテナ
  backup:
    build:
      context: backup
      dockerfile: Dockerfile
      args:
        - SIMUTRANS_VERSION=${SIMUTRANS_VERSION}
    restart: unless-stopped
    volumes:
      - ./volume-save:/app/save
    environment:
      - TZ=Asia/Tokyo
      - NETTOOL_PASSWORD=${NETTOOL_PASSWORD}
