# ベースイメージ
FROM debian:trixie-slim

# 必要なパッケージのインストール
RUN apt-get update && \
    apt-get install -y libminiupnpc-dev libpng-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# libminiupnpc.17が必要なので、誤魔化す
RUN ln -s /usr/lib/x86_64-linux-gnu/libminiupnpc.so.18 /usr/lib/x86_64-linux-gnu/libminiupnpc.so.17 && \
    ldconfig

# 作業ディレクトリの設定
WORKDIR /app

# 実行ファイルなどはホストから/app/binにマウントする想定
